### create customer
POST {{baseUrl}}/customers
Authorization: {{Authorization}}
Content-Type: application/json

{
  "firstName": "Ivan",
  "lastName": "Garcia Sainz-Aja",
  "email": "ivangsa@gmail.com",
  "addresses": [
    {
      "identifier": "Home",
      "street": "Calle del Percebe, 13",
      "city": "Madrid",
      "state": "Madrid",
      "zip": "28001",
      "country": "Spain",
      "type": "HOME"
    }
  ]
}

### update customer address
< {%
    request.variables.set("customerId", "65950b6257794e62962c8b2e")
    request.variables.set("identifier", "Home")
%}
PUT {{baseUrl}}//customers/{{customerId}}/address/{{identifier}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "identifier": "{{identifier}}",
  "street": "Calle del Percebe, 13",
  "city": "Madrid",
  "state": "Madrid",
  "zip": "28001",
  "country": "Spain",
  "type": "WORK"
}
