logging:
  level:
    org.springframework.transaction: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.MongoTransactionManager: DEBUG

MONGODB_URI: mongodb://localhost:27017/customers
